apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/Bhavesh1326/local-cloud.git
    targetRevision: main
    path: step-3-istio/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true