apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/istio/istio.git
    path: manifests/charts/istio-control/istio-discovery
    targetRevision: release-1.20
    helm:
      parameters:
        - name: global.proxy.autoInject
          value: "enabled"
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
