apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'istio-mesh'
        static_configs:
          - targets: ['istiod.istio-system.svc.cluster.local:15090']
      - job_name: 'service-a'
        static_configs:
          - targets: ['service-a.local-cloud-ns.svc.cluster.local:8080']
      - job_name: 'service-b'
        static_configs:
          - targets: ['service-b.local-cloud-ns.svc.cluster.local:8080']
      - job_name: 'service-c'
        static_configs:
          - targets: ['service-c.local-cloud-ns.svc.cluster.local:8080']