apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus
  namespace: monitoring
data:
  prometheus.yml: |
    scrape_configs:
      - job_name: 'istio-mesh'
        static_configs:
          - targets: ['istio-telemetry.istio-system.svc.cluster.local:15090']