apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: microservices
  namespace: argocd
spec:
  project: platform
  source:
    path: apps
    repoURL: https://github.com/Bhavesh1326/sre-cloud-project.git
    targetRevision: feature/kubernetes-platform
  destination:
    server: https://kubernetes.default.svc
    namespace: microservices
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
